obstacle_range: 1.5
raytrace_range: 3.0
# footprint: [[-0.108, -0.150], [-0.108, 0.150], [0.108, 0.150], [0.108, -0.150]]
# footprint: [[-0.150, -0.108], [-0.150, 0.108], [0.150, 0.108], [0.150, -0.108]]
footprint: [[-0.150, -0.15], [-0.150, 0.15], [0.150, 0.15], [0.150, -0.15]]

transform_tolerance: 10.0
resolution: 0.05 

static_map_layer:
    map_topic: map
    subscribe_to_updates: true

2d_obstacles_layer:
  observation_sources: scan
  scan: {data_type: LaserScan,
    topic: scan,
    marking: true,
    clearing: true}

# 3d_obstacles_layer: 
#   observation_sources: depth
#   depth: {data_type: PointCloud2,
#     topic: vio_slam/points2,
#     min_obstacle_height: 0.02,
#     marking: true,
#     clearing: true}

inflation_layer:
    inflation_radius: 2.0