base_global_planner: global_planner/GlobalPlanner
base_local_planner: dwa_local_planner/DWAPlannerROS
# base_local_planner: nav_core_adapter::LocalPlannerAdapter
# base_global_planner: global_planner/GlobalPlanner
# base_local_planner: nav_core_adapter::LocalPlannerAdapter
# LocalPlannerAdapter:
#   planner_name: dwb_local_planner::DWBLocalPlanner

footprint: [[-0.150, -0.15], [-0.150, 0.15], [0.150, 0.15], [0.150, -0.15]]
# footprint: [[-0.150, -0.108], [-0.150, 0.108], [0.150, 0.108], [0.150, -0.108]]
shutdown_costmaps: false

controller_frequency: 3.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

conservative_reset_dist: 0.1